// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { warnIfSupabaseKeyUrlMismatch } from "./env";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
/** Anon (public) or publishable key — must be issued for the same project as VITE_SUPABASE_URL. */
export const SUPABASE_ANON_OR_PUBLISHABLE_KEY =
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined)?.trim() ||
  (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined)?.trim();

if (SUPABASE_URL && SUPABASE_ANON_OR_PUBLISHABLE_KEY) {
  warnIfSupabaseKeyUrlMismatch(SUPABASE_URL, SUPABASE_ANON_OR_PUBLISHABLE_KEY);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL ?? "",
  SUPABASE_ANON_OR_PUBLISHABLE_KEY ?? "",
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);